In [1]:
import pandas as pd
import numpy as np
users = pd.read_csv("users.csv")
print(users.shape)
users.head()

(6040, 5)


user_id gender  age  occupation zip_code
0        0      F    1          10    48067
1        1      M   56          16    70072
2        2      M   25          15    55117
3        3      M   45           7    02460
4        4      M   25          20    55455

In [2]:

movies = pd.read_csv("movies.csv")
movies.head()

movie_id                        title  year  Animation  Children's  Comedy  \
0         0                    Toy Story  1995        1.0         1.0     1.0   
1         1                      Jumanji  1995        0.0         1.0     0.0   
2         2             Grumpier Old Men  1995        0.0         0.0     1.0   
3         3            Waiting to Exhale  1995        0.0         0.0     1.0   
4         4  Father of the Bride Part II  1995        0.0         0.0     1.0   

   Adventure  Fantasy  Romance  Drama  ...  Crime  Thriller  Horror  Sci-Fi  \
0        0.0      0.0      0.0    0.0  ...    0.0       0.0     0.0     0.0   
1        1.0      1.0      0.0    0.0  ...    0.0       0.0     0.0     0.0   
2        0.0      0.0      1.0    0.0  ...    0.0       0.0     0.0     0.0   
3        0.0      0.0      0.0    1.0  ...    0.0       0.0     0.0     0.0   
4        0.0      0.0      0.0    0.0  ...    0.0       0.0     0.0     0.0   

   Documentary  War  Musical  Mystery  Film-Noir  Western  
0          0.0  0.0      0.0      0.0        0.0      0.0  
1          0.0  0.0      0.0      0.0        0.0      0.0  
2          0.0  0.0      0.0      0.0        0.0      0.0  
3          0.0  0.0      0.0      0.0        0.0      0.0  
4          0.0  0.0      0.0      0.0        0.0      0.0  

[5 rows x 21 columns]

In [3]:
ratings = pd.read_csv("ratings.csv")
ratings.head()

user_id  movie_id  rating
0        0      1176       5
1        0       655       3
2        0       902       3
3        0      3339       4
4        0      2286       5

In [75]:
print(users.info())
print("-------------------------------------------------")
print(ratings.info())
print("-------------------------------------------------")

print(movies.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6040 entries, 0 to 6039
Data columns (total 5 columns):
user_id       6040 non-null int64
gender        6040 non-null object
age           6040 non-null int64
occupation    6040 non-null int64
zip_code      6040 non-null object
dtypes: int64(3), object(2)
memory usage: 236.1+ KB
None
-------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000209 entries, 0 to 1000208
Data columns (total 3 columns):
user_id     1000209 non-null int64
movie_id    1000209 non-null int64
rating      1000209 non-null int64
dtypes: int64(3)
memory usage: 22.9 MB
None
-------------------------------------------------
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3883 entries, 0 to 3882
Data columns (total 21 columns):
movie_id       3883 non-null int64
title          3883 non-null object
year           3883 non-null int64
Animation      3883 non-null float64
Children's     3883 non-null float64
Comedy         38

In [97]:
genre_cols = ["Animation", "Children's", 
       'Comedy', 'Adventure', 'Fantasy', 'Romance', 'Drama',
       'Action', 'Crime', 'Thriller', 'Horror', 'Sci-Fi', 'Documentary', 'War',
       'Musical', 'Mystery', 'Film-Noir', 'Western']

genre_and_title_cols = ['title'] + genre_cols 

movies[genre_and_title_cols].head()

title  Animation  Children's  Comedy  Adventure  \
0                    Toy Story        1.0         1.0     1.0        0.0   
1                      Jumanji        0.0         1.0     0.0        1.0   
2             Grumpier Old Men        0.0         0.0     1.0        0.0   
3            Waiting to Exhale        0.0         0.0     1.0        0.0   
4  Father of the Bride Part II        0.0         0.0     1.0        0.0   

   Fantasy  Romance  Drama  Action  Crime  Thriller  Horror  Sci-Fi  \
0      0.0      0.0    0.0     0.0    0.0       0.0     0.0     0.0   
1      1.0      0.0    0.0     0.0    0.0       0.0     0.0     0.0   
2      0.0      1.0    0.0     0.0    0.0       0.0     0.0     0.0   
3      0.0      0.0    1.0     0.0    0.0       0.0     0.0     0.0   
4      0.0      0.0    0.0     0.0    0.0       0.0     0.0     0.0   

   Documentary  War  Musical  Mystery  Film-Noir  Western  
0          0.0  0.0      0.0      0.0        0.0      0.0  
1          0.0  0.0      0.0      0.0        0.0      0.0  
2          0.0  0.0      0.0      0.0        0.0      0.0  
3          0.0  0.0      0.0      0.0        0.0      0.0  
4          0.0  0.0      0.0      0.0        0.0      0.0

In [98]:
toy_story_genres = movies[genre_and_title_cols].loc[movies.title == 'Toy Story'][genre_cols].iloc[0]
toy_story_genres

Animation      1.0
Children's     1.0
Comedy         1.0
Adventure      0.0
Fantasy        0.0
Romance        0.0
Drama          0.0
Action         0.0
Crime          0.0
Thriller       0.0
Horror         0.0
Sci-Fi         0.0
Documentary    0.0
War            0.0
Musical        0.0
Mystery        0.0
Film-Noir      0.0
Western        0.0
Name: 0, dtype: float64

In [99]:
et_genres = movies[genre_and_title_cols].loc[movies.title == 'E.T. the Extra-Terrestrial'][genre_cols].iloc[0]
et_genres

Animation      0.0
Children's     1.0
Comedy         0.0
Adventure      0.0
Fantasy        1.0
Romance        0.0
Drama          1.0
Action         0.0
Crime          0.0
Thriller       0.0
Horror         0.0
Sci-Fi         1.0
Documentary    0.0
War            0.0
Musical        0.0
Mystery        0.0
Film-Noir      0.0
Western        0.0
Name: 1081, dtype: float64

In [100]:
et_genres.values * toy_story_genres

Animation      0.0
Children's     1.0
Comedy         0.0
Adventure      0.0
Fantasy        0.0
Romance        0.0
Drama          0.0
Action         0.0
Crime          0.0
Thriller       0.0
Horror         0.0
Sci-Fi         0.0
Documentary    0.0
War            0.0
Musical        0.0
Mystery        0.0
Film-Noir      0.0
Western        0.0
Name: 0, dtype: float64

In [101]:
(et_genres.values * toy_story_genres).sum() # scalar product

1.0

In [102]:
pocahontas_genres = movies[genre_and_title_cols].loc[movies.title == 'Pocahontas'][genre_cols].iloc[0]
(pocahontas_genres.values * toy_story_genres).sum()


2.0

In [103]:
similarity = movies[genre_cols].values.dot(movies[genre_cols].values.T)
similarity.shape

(3883, 3883)

In [104]:
similarity_with_toy_story = similarity[0] # 0 is Toy Story
similarity_with_toy_story

array([3., 1., 1., ..., 0., 0., 0.])

In [105]:
for i in range(10):
    print(f"Similarity between Toy story and {movies.iloc[i]['title']} (index {i}) is {similarity_with_toy_story[i]}")

Similarity between Toy story and Toy Story (index 0) is 3.0
Similarity between Toy story and Jumanji (index 1) is 1.0
Similarity between Toy story and Grumpier Old Men (index 2) is 1.0
Similarity between Toy story and Waiting to Exhale (index 3) is 1.0
Similarity between Toy story and Father of the Bride Part II (index 4) is 1.0
Similarity between Toy story and Heat (index 5) is 0.0
Similarity between Toy story and Sabrina (index 6) is 1.0
Similarity between Toy story and Tom and Huck (index 7) is 1.0
Similarity between Toy story and Sudden Death (index 8) is 0.0
Similarity between Toy story and GoldenEye (index 9) is 0.0


In [106]:
from content_based_filtering.helpers.movies import get_movie_id, get_movie_name, get_movie_year
    
print (get_movie_id(movies, 'Toy Story'))
print (get_movie_id(movies, 'Die Hard'))

print (get_movie_name(movies, 0))
print (get_movie_name(movies, 1000))
print (get_movie_year(movies, 1000))

0
1023
Toy Story
Parent Trap, The
1961


In [107]:
def get_most_similar(similarity, movie_name, year=None, top=10):
    index_movie = get_movie_id(movies, movie_name, year)
    best = similarity[index_movie].argsort()[::-1]
    return [(ind, get_movie_name(movies, ind), similarity[index_movie, ind]) for ind in best[:top] if ind != index_movie]

In [108]:
get_most_similar(similarity, 'Toy Story')


[(667, 'Space Jam', 3.0),
 (3685, 'Adventures of Rocky and Bullwinkle, The', 3.0),
 (3682, 'Chicken Run', 3.0),
 (2009, 'Jungle Book, The', 3.0),
 (2011, 'Lady and the Tramp', 3.0),
 (2012, 'Little Mermaid, The', 3.0),
 (2033, 'Steamboat Willie', 3.0),
 (2072, 'American Tail, An', 3.0),
 (2073, 'American Tail: Fievel Goes West, An', 3.0)]

In [109]:
get_most_similar(similarity, 'Psycho', 1960)

[(3593, "Puppet Master III: Toulon's Revenge", 2.0),
 (2923, 'Rawhead Rex', 2.0),
 (1312, 'Believers, The', 2.0),
 (3407, "Jacob's Ladder", 2.0),
 (1957, 'Disturbing Behavior', 2.0),
 (1927, 'Poltergeist III', 2.0),
 (1926, 'Poltergeist II: The Other Side', 2.0),
 (1925, 'Poltergeist', 2.0),
 (732, 'Thinner', 2.0),
 (69, 'From Dusk Till Dawn', 2.0)]

In [110]:
def get_recommendations(user_id):
    top_movies = ratings[ratings['user_id'] == user_id].sort_values(by='rating', ascending=False).head(3)['movie_id']
    index=['movie_id', 'title', 'similarity']

    most_similars = []
    for top_movie in top_movies:
        most_similars += get_most_similar(similarity, get_movie_name(movies, top_movie), get_movie_year(movies, top_movie))

    return pd.DataFrame(most_similars, columns=index).drop_duplicates().sort_values(by='similarity', ascending=False).head(5)

get_recommendations(0)

movie_id                         title  similarity
13       773  Hunchback of Notre Dame, The         3.0
14      1526                      Hercules         3.0
27      2072             American Tail, An         3.0
26      2033              Steamboat Willie         3.0
25      2012           Little Mermaid, The         3.0

In [111]:
get_recommendations(999)


movie_id                                           title  similarity
0       166                                    First Knight         2.0
2      1451                          Smilla's Sense of Snow         2.0
3       503                                Perfect World, A         2.0
4      3197  Man Bites Dog (C'est arriv� pr�s de chez vous)         2.0
5      1458                                Devil's Own, The         2.0

## looking at similar users to find a recommendation for our targeted user 

In [25]:
nb_utilisateur  = ratings.user_id.unique().shape[0]
print('le nombre des utilisateurs unique est :  ', nb_utilisateur )

le nombre des utilisateurs unique est :   6040


In [26]:
nb_movies = ratings.movie_id.unique().shape[0]
print('le nombre des films unique est : ',  nb_movies)

le nombre des films unique est :  3706


Maintenant, on va creer une  matrice tq les lignes correspond aux utilisateurs et les colonne correspond aux films. 

In [5]:
Ratings = ratings.pivot(index = 'user_id', columns ='movie_id', values = 'rating').fillna(0)
Ratings.head()

movie_id  0     1     2     3     4     5     6     7     8     9     ...  \
user_id                                                               ...   
0          5.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  ...   
4          0.0   0.0   0.0   0.0   0.0   2.0   0.0   0.0   0.0   0.0  ...   

movie_id  3873  3874  3875  3876  3877  3878  3879  3880  3881  3882  
user_id                                                               
0          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
1          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
2          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
3          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  
4          0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0   0.0  

[5 rows x 3706 columns]

maintenant on va normaliser les donnes et les transformer en ume matrice numpy

In [27]:
R = Ratings.as_matrix()
print(R)
#calculer la moyenne 
user_ratings_mean = np.mean(R, axis = 1)
print(user_ratings_mean.size)
Ratings_demeaned = R - user_ratings_mean.reshape(-1, 1) 

[[5. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [3. 0. 0. ... 0. 0. 0.]]
6040


C:\Users\hp\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [29]:
sparsity = round(1.0 - len(ratings) / float(nb_utilisateur * nb_movies), 3)
print('The sparsity  is ' ,sparsity * 100 , '%')

The sparsity  is  95.5 %


In [48]:
from scipy.sparse.linalg import svds
U, sigma, Vt = svds(Ratings_demeaned, k = 50)
print('Size of sigma: ' , sigma.size)

Size of sigma:  50


In [49]:
sigma = np.diag(sigma)


In [50]:
print('Shape of sigma: ', sigma.shape)
print(sigma)

Shape of sigma:  (50, 50)
[[ 147.18581225    0.            0.         ...    0.
     0.            0.        ]
 [   0.          147.62154312    0.         ...    0.
     0.            0.        ]
 [   0.            0.          148.58855276 ...    0.
     0.            0.        ]
 ...
 [   0.            0.            0.         ...  574.46932602
     0.            0.        ]
 [   0.            0.            0.         ...    0.
   670.41536276    0.        ]
 [   0.            0.            0.         ...    0.
     0.         1544.10679346]]


In [45]:
print(seg)

[[ 147.18581225    0.            0.         ...    0.
     0.            0.        ]
 [   0.          147.62154312    0.         ...    0.
     0.            0.        ]
 [   0.            0.          148.58855276 ...    0.
     0.            0.        ]
 ...
 [   0.            0.            0.         ...  574.46932602
     0.            0.        ]
 [   0.            0.            0.         ...    0.
   670.41536276    0.        ]
 [   0.            0.            0.         ...    0.
     0.         1544.10679346]]


In [46]:
print('dimensions de  U: ', U.shape)
print('dimensions de v : ', V.shape)

dimensions de  U:  (6040, 50)
dimensions de v :  (50, 3706)


In [51]:
all_user_predicted_ratings = np.dot(np.dot(U, sigma), Vt) + user_ratings_mean.reshape(-1, 1)
print('All user predicted rating : ', all_user_predicted_ratings.shape)

All user predicted rating :  (6040, 3706)


In [52]:
print('Rating Dataframe column names', Ratings.columns)


Rating Dataframe column names Int64Index([   0,    1,    2,    3,    4,    5,    6,    7,    8,    9,
            ...
            3873, 3874, 3875, 3876, 3877, 3878, 3879, 3880, 3881, 3882],
           dtype='int64', name='movie_id', length=3706)


In [53]:
preds = pd.DataFrame(all_user_predicted_ratings, columns = Ratings.columns)
preds.head()

movie_id      0         1         2         3         4         5     \
0         4.288861  0.143055 -0.195080 -0.018843  0.012232 -0.176604   
1         0.744716  0.169659  0.335418  0.000758  0.022475  1.353050   
2         1.818824  0.456136  0.090978 -0.043037 -0.025694 -0.158617   
3         0.408057 -0.072960  0.039642  0.089363  0.041950  0.237753   
4         1.574272  0.021239 -0.051300  0.246884 -0.032406  1.552281   

movie_id      6         7         8         9     ...      3873      3874  \
0        -0.074120  0.141358 -0.059553 -0.195950  ...  0.027807  0.001640   
1         0.051426  0.071258  0.161601  1.567246  ... -0.056502 -0.013733   
2        -0.131778  0.098977  0.030551  0.735470  ...  0.040481 -0.005301   
3        -0.049426  0.009467  0.045469 -0.111370  ...  0.008571 -0.005425   
4        -0.199630 -0.014920 -0.060498  0.450512  ...  0.110151  0.046010   

movie_id      3875      3876      3877      3878      3879      3880  \
0         0.026395 -0.022024 -0.085415  0.403529  0.105579  0.031912   
1        -0.010580  0.062576 -0.016248  0.155790 -0.418737 -0.101102   
2         0.012832  0.029349  0.020866  0.121532  0.076205  0.012345   
3        -0.008500 -0.003417 -0.083982  0.094512  0.057557 -0.026050   
4         0.006934 -0.015940 -0.050080 -0.052539  0.507189  0.033830   

movie_id      3881      3882  
0         0.050450  0.088910  
1        -0.054098 -0.140188  
2         0.015148 -0.109956  
3         0.014841 -0.034224  
4         0.125706  0.199244  

[5 rows x 3706 columns]

In [66]:
def recommend_movies(predictions, userid, movies, original_ratings, num_recommendations):
   
    user_row_number = userid - 1 
    sorted_user_predictions = predictions.iloc[user_row_number].sort_values(ascending=False) 
    
    user_data = original_ratings[original_ratings.user_id == (userid)]
    user_full = (user_data.merge(movies, how = 'left', left_on = 'movie_id', right_on = 'movie_id').
                     sort_values(['rating'], ascending=False)
                 )

    print('User {0} has already rated {1} movies.'.format(userid, user_full.shape[0]))
    print('Recommending highest {0} predicted ratings movies not already rated.'.format(num_recommendations))
    
    recommendations = (movies[~movies['movie_id'].isin(user_full['movie_id'])].
         merge(pd.DataFrame(sorted_user_predictions).reset_index(), how = 'left',
               left_on = 'movie_id',
               right_on = 'movie_id').
         rename(columns = {user_row_number: 'Predictions'}).
         sort_values('Predictions', ascending = False).
                       iloc[:num_recommendations, :-1]
                      )

    return user_full, recommendations

In [67]:
already_rated, predictions = recommend_movies(preds, 150, movies, ratings, 20)


User 150 has already rated 471 movies.
Recommending highest 20 predicted ratings movies not already rated.


In [68]:
already_rated.head(20)


user_id  movie_id  rating                                        title  \
0        150      1159       5                                 Delicatessen   
58       150      3826       5                          Way of the Gun, The   
91       150      2179       5                              Say Anything...   
352      150       293       5                                 Pulp Fiction   
154      150      1656       5                            Good Will Hunting   
87       150      1482       5  Austin Powers: International Man of Mystery   
86       150      2176       5                                 Working Girl   
356      150      2789       5                              American Beauty   
358      150      1034       5                     Long Kiss Goodnight, The   
359      150       437       5                           Dazed and Confused   
360      150        49       5                          Usual Suspects, The   
245      150      1776       5                                  Zero Effect   
157      150      1593       5                                  Chasing Amy   
243      150      3379       5                        Good Morning, Vietnam   
77       150      1270       5                       Some Kind of Wonderful   
159      150      1529       5                     My Best Friend's Wedding   
161      150      3248       5                                  Wonder Boys   
162      150      1595       5                              Full Monty, The   
381      150      1182       5                                       Aliens   
69       150      1468       5                          Grosse Pointe Blank   

     year  Animation  Children's  Comedy  Adventure  Fantasy  ...  Crime  \
0    1991        0.0         0.0     1.0        0.0      0.0  ...    0.0   
58   2000        0.0         0.0     0.0        0.0      0.0  ...    1.0   
91   1989        0.0         0.0     1.0        0.0      0.0  ...    0.0   
352  1994        0.0         0.0     0.0        0.0      0.0  ...    1.0   
154  1997        0.0         0.0     0.0        0.0      0.0  ...    0.0   
87   1997        0.0         0.0     1.0        0.0      0.0  ...    0.0   
86   1988        0.0         0.0     1.0        0.0      0.0  ...    0.0   
356  1999        0.0         0.0     1.0        0.0      0.0  ...    0.0   
358  1996        0.0         0.0     0.0        0.0      0.0  ...    0.0   
359  1993        0.0         0.0     1.0        0.0      0.0  ...    0.0   
360  1995        0.0         0.0     0.0        0.0      0.0  ...    1.0   
245  1998        0.0         0.0     1.0        0.0      0.0  ...    0.0   
157  1997        0.0         0.0     0.0        0.0      0.0  ...    0.0   
243  1987        0.0         0.0     1.0        0.0      0.0  ...    0.0   
77   1987        0.0         0.0     0.0        0.0      0.0  ...    0.0   
159  1997        0.0         0.0     1.0        0.0      0.0  ...    0.0   
161  2000        0.0         0.0     1.0        0.0      0.0  ...    0.0   
162  1997        0.0         0.0     1.0        0.0      0.0  ...    0.0   
381  1986        0.0         0.0     0.0        0.0      0.0  ...    0.0   
69   1997        0.0         0.0     1.0        0.0      0.0  ...    1.0   

     Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  Film-Noir  \
0         0.0     0.0     1.0          0.0  0.0      0.0      0.0        0.0   
58        1.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
91        0.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
352       0.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
154       0.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
87        0.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
86        0.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
356       0.0     0.0     0.0          0.0  0.0      0.0      0.0        0.0   
358       1.0     0.0     0.

In [69]:
predictions

movie_id                                              title  year  \
2299      2647                                       Ghostbusters  1984   
1620      1892                                           Rain Man  1988   
2546      2918                           Who Framed Roger Rabbit?  1988   
1057      1238                                       Shining, The  1980   
1026      1190                                     Apocalypse Now  1979   
1383      1627                                      Boogie Nights  1997   
931       1074                                            Platoon  1986   
487        586                                 Dances with Wolves  1990   
1162      1366                                               Jaws  1975   
1654      1928                                      Exorcist, The  1973   
1049      1227                                      Graduate, The  1967   
1020      1180                            Raiders of the Lost Ark  1981   
3170      3602                                    Blazing Saddles  1974   
2701      3091                                           Magnolia  1999   
2716      3107                           Talented Mr. Ripley, The  1999   
1073      1258                                 Young Frankenstein  1974   
1088      1279                                Killing Fields, The  1984   
116        148                                          Apollo 13  1995   
2524      2890                                         Fight Club  1999   
206        262  Like Water for Chocolate (Como agua para choco...  1992   

      Animation  Children's  Comedy  Adventure  Fantasy  Romance  Drama  ...  \
2299        0.0         0.0     1.0        0.0      0.0      0.0    0.0  ...   
1620        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
2546        1.0         0.0     0.0        1.0      0.0      0.0    0.0  ...   
1057        0.0         0.0     0.0        0.0      0.0      0.0    0.0  ...   
1026        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
1383        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
931         0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
487         0.0         0.0     0.0        1.0      0.0      0.0    1.0  ...   
1162        0.0         0.0     0.0        0.0      0.0      0.0    0.0  ...   
1654        0.0         0.0     0.0        0.0      0.0      0.0    0.0  ...   
1049        0.0         0.0     0.0        0.0      0.0      1.0    1.0  ...   
1020        0.0         0.0     0.0        1.0      0.0      0.0    0.0  ...   
3170        0.0         0.0     1.0        0.0      0.0      0.0    0.0  ...   
2701        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
2716        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
1073        0.0         0.0     1.0        0.0      0.0      0.0    0.0  ...   
1088        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
116         0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
2524        0.0         0.0     0.0        0.0      0.0      0.0    1.0  ...   
206         0.0         0.0     0.0        0.0      0.0      1.0    1.0  ...   

      Crime  Thriller  Horror  Sci-Fi  Documentary  War  Musical  Mystery  \
2299    0.0       0.0     1.0     0.0          0.0  0.0      0.0      0.0   
1620    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
2546    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1057    0.0       0.0     1.0     0.0          0.0  0.0      0.0      0.0   
1026    0.0       0.0     0.0     0.0          0.0  1.0      0.0      0.0   
1383    0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
931     0.0       0.0     0.0     0.0          0.0  1.0      0.0      0.0   
487     0.0       0.0     0.0     0.0          0.0  0.0      0.0      0.0   
1162    0.0       0.0     1.0     0.0          0.0  0.0 